# Generated by Django 6.0.7 on 2026-08-03 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_remove_cliente_direccion_remove_cliente_email_and_more'),
        ('paquetes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateField()),
                ('cantidad_personas', models.IntegerField()),
                ('estado', models.CharField(default='Pendiente', max_length=30)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='clientes.cliente')),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='paquetes.paqueteturistico')),
            ],
        ),
    ]
