# Generated by Django 6.0.7 on 2026-08-03 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuiaTuristico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('experiencia', models.CharField(max_length=100)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guias', to='destinos.destino')),
            ],
        ),
    ]
