# Generated by Django 6.0.7 on 2026-07-21 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cat', models.CharField(max_length=40)),
                ('descripcion_cat', models.TextField(max_length=200)),
                ('estado_cat', models.BooleanField(default=True)),
            ],
        ),
    ]
