# Generated by Django 6.0.7 on 2026-08-03 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pagos', '0001_initial'),
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='reservas.reserva'),
        ),
    ]
